name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        env:
            TZ: 'Asia/Seoul'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1' # 원하는 Node.js 버전으로 변경 가능

            - name: Install Android SDK
              shell: pwsh
              run: |
                  Write-Host "Installing Android SDK..."

                  $sdkPath = "$env:HOME\android-sdk"

                  if (Test-Path $sdkPath) {
                      Remove-Item -Recurse -Force $sdkPath
                  }

                  New-Item -ItemType Directory -Force -Path $sdkPath
                  Set-Location -Path $sdkPath

                  Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-8512546_latest.zip" -OutFile "cmdline-tools.zip"
                  Expand-Archive -Path "cmdline-tools.zip" -DestinationPath "$sdkPath\cmdline-tools" -Force
                  Remove-Item -Path "cmdline-tools.zip"

                  $env:ANDROID_HOME = $sdkPath
                  $env:PATH += ";$sdkPath\cmdline-tools\latest\bin"

                  & "$sdkPath\cmdline-tools\latest\bin\sdkmanager.bat" --update
                  & "$sdkPath\cmdline-tools\latest\bin\sdkmanager.bat" "platform-tools" "platforms;android-30" "build-tools;30.0.3"

            - name: Install Dependencies
              run: npm install
              shell: cmd

            - name: Run Tests on Real Device
              run: |
                  echo "Running tests on a real device..."
                  node project/test.js
              shell: cmd
