name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  npm install -g appium
                  npm install

            - name: Install Android SDK Platform Tools
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget unzip
                  wget https://dl.google.com/android/repository/platform-tools_r31.0.3-linux.zip -O platform-tools.zip
                  unzip platform-tools.zip -d $HOME/android-sdk/
                  echo "export PATH=$PATH:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

            - name: Install Android Emulator
              run: |
                  wget https://dl.google.com/android/repository/emulator-linux-x86_64-9216767.zip -O emulator.zip
                  unzip emulator.zip -d $HOME/android-sdk/
                  echo "export PATH=$PATH:$HOME/android-sdk/emulator" >> $GITHUB_ENV

            - name: Set up Android Emulator
              run: |
                  echo "no" | $HOME/android-sdk/emulator/emulator -avd test -no-audio -no-window &
                  adb wait-for-device
                  adb shell input keyevent 82

            - name: Run Appium Server
              run: |
                  appium --use-plugins element-wait --no-reset --port 4723 &
                  sleep 10 # Appium 서버가 시작될 시간을 기다립니다.

            - name: Run Tests
              run: |
                  node project/test.js

            - name: Clean up
              run: |
                  adb -s emulator-5554 emu kill
