name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        env:
            TZ: 'Asia/Seoul'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1' # 원하는 Node.js 버전으로 변경 가능

            - name: Install Appium
              run: npm install -g appium
              shell: cmd

            - name: Install Appium Drivers
              run: |
                  appium driver install uiautomator2
              shell: cmd

            - name: Start Appium Server
              run: start appium --port 4725
              shell: cmd

            - name: Install Dependencies
              run: npm install
              shell: cmd

            - name: Run Tests on Real Device
              run: |
                  echo "Running tests on a real device..."
                  node project/test.js
              shell: cmd
