name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16' # 원하는 Node.js 버전을 지정

            - name: Install dependencies
              run: |
                  npm install -g appium
                  npm install

            - name: Install Android SDK
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget unzip
                  wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
                  unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
                  yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
                  $HOME/android-sdk/cmdline-tools/bin/sdkmanager --update
                  $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

            - name: Set up Android Emulator
              run: |
                  echo "no" | $HOME/android-sdk/emulator/emulator -avd test -no-audio -no-window &
                  adb wait-for-device
                  adb shell input keyevent 82

            - name: Run Appium Server
              run: |
                  appium --use-plugins element-wait --no-reset &
                  sleep 10 # Appium 서버가 시작될 시간을 기다립니다.

            - name: Run Appium Tests
              run: |
                  node project/test.js

            - name: Clean up
              run: |
                  adb -s emulator-5554 emu kill
