name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        env:
            TZ: 'Asia/Seoul'
            ANDROID_HOME: 'C:\path\to\android-sdk' # Android SDK 경로
            ANDROID_SDK_ROOT: 'C:\path\to\android-sdk' # Android SDK 경로

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1' # 원하는 Node.js 버전으로 변경 가능

            - name: Install Dependencies
              run: npm install
              shell: cmd

            - name: Run Tests on Real Device
              run: |
                  set "PATH=%PATH%;%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools"
                  echo "ANDROID_HOME is set to %ANDROID_HOME%"
                  echo "PATH is set to %PATH%"
                  echo "실제 디바이스에서 테스트를 실행합니다..."
                  node project/test.js
              shell: cmd
