name: CI/CD for Appium Android Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16' # 원하는 Node.js 버전으로 변경 가능

            - name: Install dependencies
              run: npm install

            - name: Install Appium
              run: npm install -g appium

            - name: Install Android SDK
              run: |
                  sudo apt-get update
                  sudo apt-get install -y openjdk-11-jdk wget unzip
                  wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
                  unzip commandlinetools-linux-7583922_latest.zip -d ~/android-sdk
                  yes | ~/android-sdk/cmdline-tools/bin/sdkmanager --licenses
                  ~/android-sdk/cmdline-tools/bin/sdkmanager --update
                  ~/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30"  # Android API Level에 맞게 조정

            - name: Start Appium Server
              run: |
                  appium &  # Appium 서버를 백그라운드에서 실행
                  sleep 10  # 서버가 완전히 시작될 때까지 대기

            - name: Run tests
              run: node project/test.js # 테스트 스크립트를 실행

            - name: Stop Appium Server
              run: pkill -f appium # Appium 서버를 종료
