# name: Android Appium Test

# on:
#     push:
#         branches:
#             - main # 원하는 브랜치에 push될 때 실행
#     pull_request:
#         branches:
#             - main # main 브랜치로의 PR일 때 실행

# jobs:
#     test:
#         runs-on: ubuntu-latest

#         services:
#             # Appium 서버를 Docker 컨테이너로 실행
#             appium:
#                 image: appium/appium
#                 ports:
#                     - 4723:4723
#                 options: >-
#                     --health-cmd "curl --fail http://localhost:4723/wd/hub/status || exit 1"
#                     --health-interval 10s
#                     --health-timeout 5s
#                     --health-retries 5

#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v3

#             - name: Set up JDK 11
#               uses: actions/setup-java@v3
#               with:
#                   java-version: 11

#             - name: Set up Android SDK
#               uses: android-actions/setup-android@v2
#               with:
#                   api-level: 30
#                   build-tools: 30.0.2
#                   target: default
#                   emulator-name: test_emulator

#             - name: Start Android Emulator
#               run: |
#                   $ANDROID_HOME/emulator/emulator -avd test_emulator -no-snapshot-load -noaudio -no-boot-anim -no-window &
#                   adb wait-for-device
#                   adb shell input keyevent 82

#             - name: Install dependencies
#               run: npm install

#             - name: Run Android UI Tests
#               run: node project/test.js # project 폴더의 test.js 파일을 실행
