name: Android Appium Tests

on:
    schedule:
        - cron: '0 23 * * 0-4' # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행 (KCT: 8:00 AM)
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    App-test:
        runs-on: self-hosted
        env:
            TZ: 'Asia/Seoul'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1' # 원하는 Node.js 버전으로 변경 가능

            - name: Install Yarn
              run: npm install -g yarn
              shell: cmd

            - name: Install Appium
              run: yarn global add appium
              shell: cmd

            - name: Install Appium Drivers
              run: appium driver install uiautomator2
              shell: cmd

            - name: Install Dependencies
              run: yarn install
              shell: cmd

            - name: Run Appium Test
              run: |
                  start /B appium --port 4725
                  echo "Running App tests on a real device..."
                  yarn mocha scheduled/app/Action_signup.js
                  yarn mocha scheduled/app/Action_store_매장.js
              shell: cmd

    tableorder-test:
        runs-on: self-hosted
        needs: App-test # store-tests가 완료되면 실행
        env:
            TZ: 'Asia/Seoul'

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1'

            - name: Install Yarn
              run: npm install -g yarn
              shell: cmd

            - name: Install Appium
              run: yarn global add appium
              shell: cmd

            - name: Install Appium Drivers
              run: appium driver install uiautomator2
              shell: cmd

            - name: Install Dependencies
              run: yarn install
              shell: cmd

            - name: Run Appium Test
              run: |
                  start /B appium --port 4727
                  echo "Running Tableorder tests on a real device..."
                  yarn mocha scheduled/tableorder/Action_order_후불.js
              shell: cmd
