name: Android Appium Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest # 또는 macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  npm install -g appium
                  npm install

            - name: Set up Android SDK
              run: |
                  echo "sdkmanager --install 'system-images;android-29;google_apis;x86_64'" >> $GITHUB_ENV
                  echo "sdkmanager --install emulator" >> $GITHUB_ENV

            - name: Create and launch emulator
              run: |
                  echo "no" | avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64"
                  emulator -avd test -no-audio -no-window &
                  adb wait-for-device
                  adb shell input keyevent 82

            - name: Run Appium Server
              run: |
                  appium --use-plugins element-wait --no-reset --port 4723 &
                  sleep 10 # Appium 서버가 시작될 시간을 기다립니다.

            - name: Run Tests
              run: |
                  node project/test.js

            - name: Clean up
              run: |
                  adb -s emulator-5554 emu kill
