name: Android Appium Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            appium:
                image: appium/appium::latest
                ports:
                    - 4723:4723
                options: >-
                    --health-cmd "curl --fail http://localhost:4723/wd/hub/status || exit 1"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin' # 또는 원하는 Java 배포판 (e.g., 'zulu')
                  java-version: '11'

            - name: Set up Android SDK
              uses: android-actions/setup-android@v2
              with:
                  api-level: 30
                  build-tools: 30.0.2

            - name: Create AVD
              run: |
                  echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64"
                  $ANDROID_HOME/emulator/emulator -avd test_emulator -no-snapshot-load -noaudio -no-boot-anim -no-window &
                  adb wait-for-device
                  adb shell input keyevent 82

            - name: Install dependencies
              run: npm install

            - name: Run Android UI Tests
              run: node project/test.js

            - name: Archive Test Results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: test-results
                  path: ./test-results

            - name: Archive Screenshots
              if: failure()
              uses: actions/upload-artifact@v3
              with:
                  name: screenshots
                  path: ./screenshots
